apiVersion: user.azuread.upbound.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/user
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: J. Doe
    mailNickname: jdoe
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    userPrincipalName: jdoe@hashicorp.com

---

